### ISSUE TITLE
All tests seem to fail in the first command.

### ISSUE THREAD

**Issue by LinoBigatti** [alunduil/etest#73]
Currently all tests fail, reporting the failed command as the first to be executed. I cant find any pattern, so it smells like a docker issue. Any insight on more ways to test this would be appreciated.

**Comment by alunduil** [comment]
Can you provide the commands you're running and a paste of the output?  That should allow me to see what's going on and see if I can reproduce it on my machine (I haven't used Gentoo in years so that might be interesting too).

**Comment by LinoBigatti** [comment]
Im currently testing against ``x11-apps/xcur2png`` and ``games-emulation/np2kai``. The former is the lightest ebuild that I could find and the latter is my own ebuild. I have made [a gist](https://gist.github.com/LinoBigatti/356b53daadb9b0589967088d16bce7ca) with the logs. Both are in ``::guru``. However, from my testing I believe any ebuild should fail in this way.

**Comment by alunduil** [comment]
Hmm, the gist looks like it's failing to write the use flag configurations or failing on the step after that.  We'll definitely need to add more verbose output to continue investigating.  I'll see if I can simplify the test suite so that we can add these as test cases then it should be a matter of making the failures include which step failed somehow.  Let me know if you want to find a more synchronous media to work through some of this as well.

**Comment by LinoBigatti** [comment]
Sure. Something that could also work is stopping the work half way and connecting manually to check for errors. For better communication, you can reach to me via:
Email: ``linobigatti@protonmail.com``
Matrix: ``@linobigatti:matrix.org``
Discord: ``lino#1234``
If you have another preferred communication method let me know and I can join there.

**Comment by LinoBigatti** [comment]
Closed by #78
