### ISSUE TITLE
Document minimum Python version

### ISSUE THREAD

**Issue by pombredanne** [alunduil/etest#98]
The code depends on features in 3.8, yet installs fine on 3.6 but does not work there

**Comment by alunduil** [comment]
Thanks for the heads up.  I'll throw together a pull request that should fix this up real quick.

**Comment by alunduil** [comment]
Actually, what and how did you do the installation because we do have a python-3.8 dependency listed in the pyproject.toml file.  We're still in the process of getting this setup for a new release version but definitely making this clear or fail installation would be a good idea.

Please let me know the commands you used to do the installation so we can make that flow more accurate.

Thanks.
